### PR TITLE
Fix: wrong choose signal.

### PR DESCRIPTION
**Pull request by sioncojp**
When you see it, you will know.

### CODE REVIEW

**Comment by sioncojp** [comment]
Please wait until I resolve that there is one thing that bothers me.
sorry.

**Comment by sioncojp** [comment]
OK. Resolved.
Please review!

**Comment by lestrrat** [comment]
No, this is not what SignalOnHUP is about.
SignalOnHUP is "what start_server sends when it receives a HUP".
The default behavior is to send a TERM signal when HUP is received.

**Comment by sioncojp** [comment]
I got it.  Thank you!!!
Close this PR.

**Comment by sioncojp** [comment]
Sorry, I've a question.
Why did you choise default not `signalOnHUP = syscall.SIGHUP` but `signalOnHUP = syscall.SIGTERM`?

**Comment by lestrrat** [comment]
The entire design of the go version was based on Perl5's start_server command, so you probably should go ask the author of the original for the _real_ "why".

I'm guessing that it's safer to make the default action "properly kill" the backend program, and force the user to explicitly specify what signal should be used for the backend program to be notified of a graceful restart.

**Comment by sioncojp** [comment]
Thanks for the follow up!

**Pull request closed without merging**
